[package]
name = "embed2"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
surrealdb = { version = "2.3", features = ["kv-mem"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
