[package]
name = "serde_json_sample"
version = "0.1.0"
authors = [""]
edition = "2018"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
