apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: pgitem
  annotations:
    version: v0.0.1
spec:
  components:
    - name: app
      type: component
      properties:
        image: file://./build/pgitem_s.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 1
        - type: link
          properties:
            target: 
              name: postgres
              config:
                - name: default-pg
            namespace: wasmcloud
            package: postgres
            interfaces: [query]
    - name: postgres
      type: capability
      properties:
        image: ghcr.io/wasmcloud/sqldb-postgres:0.10.0
