[package]
name = "sample"
version = "0.1.0"
edition = "2018"

[dependencies]
tide = "0.16"
async-std = { version = "1.9", features = ["attributes"] }
serde = "1.0"
serde_json = "1.0"
uuid = { version = "0.8", features = ["serde", "v4"] }

juniper = "0.15"
