apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: sample1
  annotations:
    version: v0.0.1
    description: ''
spec:
  components:
    - name: http-component
      type: component
      properties:
        image: file://./build/sample1_s.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 1

    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.27.0
      traits:
        - type: link
          properties:
            target:
              name: http-component
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source:
              config:
                - name: default-http
                  properties:
                    address: 0.0.0.0:8000
