[package]
name = "iris"
version = "0.1.0"
edition = "2024"
default-run = "train"

[dependencies]
candle-core = { version = "0.11.0", features = ["metal"] }
candle-nn = { version = "0.11.0", features = ["metal"] }
csv = "1.4.0"
rand = "0.10.3"

[[bin]]
name = "train"
path = "./src/train.rs"

[[bin]]
name = "train1"
path = "./src/train1.rs"

[[bin]]
name = "train2"
path = "./src/train2.rs"

[[bin]]
name = "eval"
path = "./src/eval.rs"

[[bin]]
name = "eval1"
path = "./src/eval1.rs"

[[bin]]
name = "eval2"
path = "./src/eval2.rs"