[package]
name = "embed_adt"
version = "0.1.0"
edition = "2024"
default-run = "main"

[dependencies]
surrealdb = { version = "3.2.4", features = ["kv-mem"] }
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
serde = "1"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "main2"
path = "src/main2.rs"

[[bin]]
name = "main3"
path = "src/main3.rs"

[[bin]]
name = "main4"
path = "src/main4.rs"
