[package]
name = "ratio_json"
version = "0.1.0"
edition = "2021"

[dependencies]
num-rational = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
