/**
 * This class is generated by jOOQ
 */
package sample.model.ticket;

/**
 * A class modelling foreign key relationships between tables of the <code>ticket</code> 
 * schema
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<sample.model.ticket.tables.records.TicketsRecord> KEY_TICKETS_PRIMARY = UniqueKeys0.KEY_TICKETS_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<sample.model.ticket.tables.records.TicketsRecord> KEY_TICKETS_PRIMARY = createUniqueKey(sample.model.ticket.tables.Tickets.TICKETS, sample.model.ticket.tables.Tickets.TICKETS.TICKET_CODE);
	}
}
