/**
 * This class is generated by jOOQ
 */
package sample.model.ticket;

/**
 * Convenience access to all tables in ticket
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table ticket.tickets
	 */
	public static final sample.model.ticket.tables.Tickets TICKETS = sample.model.ticket.tables.Tickets.TICKETS;

	/**
	 * The table ticket.used_tickets
	 */
	public static final sample.model.ticket.tables.UsedTickets USED_TICKETS = sample.model.ticket.tables.UsedTickets.USED_TICKETS;
}
