/**
 * This class is generated by jOOQ
 */
package sample.model.ticket.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsedTicketsRecord extends org.jooq.impl.TableRecordImpl<sample.model.ticket.tables.records.UsedTicketsRecord> implements org.jooq.Record3<java.lang.String, java.lang.String, java.sql.Timestamp> {

	private static final long serialVersionUID = -1465387437;

	/**
	 * Setter for <code>ticket.used_tickets.ticket_code</code>.
	 */
	public void setTicketCode(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ticket.used_tickets.ticket_code</code>.
	 */
	public java.lang.String getTicketCode() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>ticket.used_tickets.user_id</code>.
	 */
	public void setUserId(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ticket.used_tickets.user_id</code>.
	 */
	public java.lang.String getUserId() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>ticket.used_tickets.used_date</code>.
	 */
	public void setUsedDate(java.sql.Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ticket.used_tickets.used_date</code>.
	 */
	public java.sql.Timestamp getUsedDate() {
		return (java.sql.Timestamp) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.String, java.lang.String, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.String, java.lang.String, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return sample.model.ticket.tables.UsedTickets.USED_TICKETS.TICKET_CODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return sample.model.ticket.tables.UsedTickets.USED_TICKETS.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field3() {
		return sample.model.ticket.tables.UsedTickets.USED_TICKETS.USED_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getTicketCode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value3() {
		return getUsedDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsedTicketsRecord value1(java.lang.String value) {
		setTicketCode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsedTicketsRecord value2(java.lang.String value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsedTicketsRecord value3(java.sql.Timestamp value) {
		setUsedDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsedTicketsRecord values(java.lang.String value1, java.lang.String value2, java.sql.Timestamp value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UsedTicketsRecord
	 */
	public UsedTicketsRecord() {
		super(sample.model.ticket.tables.UsedTickets.USED_TICKETS);
	}

	/**
	 * Create a detached, initialised UsedTicketsRecord
	 */
	public UsedTicketsRecord(java.lang.String ticketCode, java.lang.String userId, java.sql.Timestamp usedDate) {
		super(sample.model.ticket.tables.UsedTickets.USED_TICKETS);

		setValue(0, ticketCode);
		setValue(1, userId);
		setValue(2, usedDate);
	}
}
