[package]
name = "iris"
version = "0.1.0"
edition = "2021"
default-run = "main"

[dependencies]
tch = "0.15"
csv = "1.3"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "main2"
path = "src/main2.rs"
