
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sample-pod-read-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sample-read-pods
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: sample-pod-read-role
  apiGroup: rbac.authorization.k8s.io
