kind: Service
apiVersion: v1
metadata:
  name: kafka1
  labels:
    app: kafka1
spec:
  selector:
    app: kafka1
  ports:
  - protocol: TCP
    name: internal
    port: 9092
    targetPort: 9092
  - protocol: TCP
    name: external
    port: 9094
    targetPort: 9094
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka1
  labels:
    app: kafka1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka1
  template:
    metadata:
      labels:
        app: kafka1
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka
        ports:
        - containerPort: 9092
          name: internal
        - containerPort: 9094
          name: external
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "localhost:32181"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka1:9092,EXTERNAL://localhost:9094"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
      - name: zookeeper
        image: confluentinc/cp-zookeeper
        ports:
        - containerPort: 32181
          name: client
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "32181"
