apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: keyvalue_sample1
  annotations:
    version: v0.0.1
spec:
  components:
    - name: count
      type: component
      properties:
        image: file://./build/keyvalue_sample1_s.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 1
        - type: link
          properties:
            namespace: wasi
            package: keyvalue
            interfaces: [atomics, store]
            target:
              name: kvnats
              config:
              - name: wasi-keyvalue-config
                properties:
                  bucket: wasmcloud
                  enable_bucket_auto_create: 'true'

    - name: kvnats
      type: capability
      properties:
        image: ghcr.io/wasmcloud/keyvalue-nats:0.4.0
    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.27.0
      traits:
        - type: link
          properties:
            target:
              name: count
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source:
              config:
                - name: default-http
                  properties:
                    address: 0.0.0.0:8000
