#!/bin/sh

INDENT="    "
CONF_DIR=/tmp/conf
CONTAINER_CONF_DIR=/conf
TWEMPROXY_IMAGE=sample/twemproxy:0.1

CONTAINER_REDIS_LIST="redis1 redis2"
CONTAINER_TWEMPROXY=twemproxy1

REDIS_SERVERS=""

for s in $CONTAINER_REDIS_LIST
do
  if test -z `docker start $s`; then
    docker run --name $s -d redis
  else
    echo start $s
  fi

  REDIS_SERVERS="$REDIS_SERVERS$INDENT- `docker inspect -f '{{.NetworkSettings.IPAddress}}' $s`:6379:1\n"
done

sed -e "s/#{SERVERS}/$REDIS_SERVERS/g" nutcracker.yml.tpl > $CONF_DIR/nutcracker.yml

if test -z `docker start $CONTAINER_TWEMPROXY`; then
  docker run --name $CONTAINER_TWEMPROXY -d -p 6379:6379 -v $CONF_DIR:$CONTAINER_CONF_DIR $TWEMPROXY_IMAGE nutcracker -s 22211 -c $CONTAINER_CONF_DIR/nutcracker.yml
else
  echo start $CONTAINER_TWEMPROXY
fi
