[package]
name = "sample"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "*", features = ["full"] }
juniper = "0.15"
elasticsearch = "7.14.0-alpha.1"
serde = "~1"
serde_json = "~1"
