[package]
name = "sample"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "*", features = ["full"] }
elasticsearch = "7.12.1-alpha.1"
# elasticsearch = "8.0.0-alpha.1" # not found
serde = "~1"
serde_json = "~1"