apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: sample
  name: sample
  namespace: default
spec:
  selector:
    matchLabels:
      app: sample
  replicas: 1
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - image: sample
        name: sample
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: sample
  namespace: default
  labels:
    service: sample
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: sample
